version: '3.1'

services:
  #mariadb service
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
 
  #GUI for mariadb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080